### ISSUE TITLE
Header change aspects in each page

### ISSUE THREAD

**Issue by MarcoTribuz** [Realise-Formation-Digital/-Bootstrap-TravelAgency#8]

**Comment by Abreha21** [comment]
Bonjour Marco, je t'écris pour savoir qu'est-ce que je dois modifier dans le header, 'est-ce qu'il s'agit du font ??

**Comment by MarcoTribuz** [comment]
Oui abreha enfait le font de le header, il change touts le temps, est.ce que tu peut regardè ca? merci!
